version: '3.9'
services:
  app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: django-app:v1
    volumes:
      - ./app:/app
    env_file:
      - /app/.env
    ports:
      - 8000:8000
    command: sh -c "chmod +x /app/config/migrate.sh && sh /app/config/migrate.sh && /app/config/entrypoint.sh"
  db:
    image: postgres:13.11-alpine3.17
    restart: always
    command: -p 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - /app/.env

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "django_db", "U", "devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: